os:
  - linux
  - osx

language: python

python:
  - "3.7"

node_js:
  - "stable"

install:
  - "npm install"
  - "pip install -r requirements.txt"

cache:
  directories:
    - "node_modules"

script:
  - "npm test"
  - "pytest"

notifications:
  webhooks:
    - https://travis-tg.herokuapp.com/u/-422708181/force
