os:
  - linux
  - osx

language: python

python:
  - "3.7"

node_js:
  - "stable"

jobs:
  include:
    - os: linux
      python: 3.7
      env: TOXENV=py37
    - os: osx
      language: generic
      env: TOXENV=py37

install:
  - "npm install"
  - ./install.sh
  - "pip install -r requirements.txt"

cache:
  directories:
    - "node_modules"

script:
  - "npm test"
  - "pytest"

notifications:
  webhooks:
    - https://travis-tg.herokuapp.com/u/-422708181/force
